<div class="jumbotron" style="margin-top: 25px;">
    <h1>Search</h1>

    <?php
    $form->prepare();
    $fileElement = $form->get('image-file');
    echo $this->form()->openTag($form);
    ?>

    <div class="form-element">
        <?= $this->formLabel($fileElement) ?>
        <?= $this->formFile($fileElement) ?>
        <?= $this->formElementErrors($fileElement) ?>
    </div>

    <button type="submit" class="btn btn-primary">Search</button>

    <?= $this->form()->closeTag() ?>

</div>