<div class="jumbotron" style="margin-top: 25px;">
    <h1>Search</h1>

    <form action="/results/" method="post">

        <div class="form-group input-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="fileUpload" accept="image/*" name="image">
                <label class="custom-file-label" for="fileUpload">Choose image</label>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Search</button>

    </form>
</div>